services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: pginbox
      POSTGRES_USER: pginbox
      POSTGRES_PASSWORD: pginbox
    ports:
      - "5499:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
