/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  ip_address: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: Int8;
}

export interface Attachments {
  content: string | null;
  content_type: string | null;
  filename: string | null;
  id: Generated<Int8>;
  message_id: Int8;
  size_bytes: number | null;
}

export interface EmailVerificationTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token_hash: string;
  user_id: Int8;
}

export interface Lists {
  id: Generated<number>;
  name: string;
}

export interface Messages {
  body: string | null;
  from_email: string | null;
  from_name: string | null;
  id: Generated<Int8>;
  in_reply_to: string | null;
  list_id: number;
  message_id: string;
  refs: string[] | null;
  sent_at: Timestamp | null;
  sent_at_approx: Generated<boolean>;
  subject: string | null;
  thread_id: string;
}

export interface PasswordResetTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token_hash: string;
  user_id: Int8;
}

export interface People {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface PeopleEmails {
  email: string;
  id: Generated<number>;
  person_id: number;
}

export interface SchemaMigrations {
  version: string;
}

export interface Threads {
  last_activity_at: Timestamp | null;
  list_id: number;
  message_count: Generated<number>;
  started_at: Timestamp | null;
  subject: string | null;
  thread_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  disable_reason: string | null;
  disabled_at: Timestamp | null;
  display_name: string | null;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<Int8>;
  last_login_at: Timestamp | null;
  password_hash: string;
  status: string;
}

export interface DB {
  auth_sessions: AuthSessions;
  attachments: Attachments;
  email_verification_tokens: EmailVerificationTokens;
  lists: Lists;
  messages: Messages;
  password_reset_tokens: PasswordResetTokens;
  people: People;
  people_emails: PeopleEmails;
  schema_migrations: SchemaMigrations;
  threads: Threads;
  users: Users;
}
