/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AnalyticsByDow {
  dow: number | null;
  list_id: number | null;
  messages: Int8 | null;
}

export interface AnalyticsByHour {
  hour: number | null;
  list_id: number | null;
  messages: Int8 | null;
}

export interface AnalyticsByMonth {
  list_id: number | null;
  messages: Int8 | null;
  month: number | null;
  year: number | null;
}

export interface AnalyticsMessagesLast24h {
  messages: Int8 | null;
  singleton_id: number | null;
}

export interface AnalyticsSummary {
  list_id: number | null;
  months_ingested: Int8 | null;
  months_set: string[] | null;
  total_messages: Int8 | null;
  total_threads: Int8 | null;
  unique_senders: Int8 | null;
}

export interface AnalyticsTopSenders {
  from_email: string | null;
  from_name: string | null;
  list_id: number | null;
  message_count: Int8 | null;
}

export interface Attachments {
  content: string | null;
  content_type: string | null;
  filename: string | null;
  id: Generated<Int8>;
  message_id: Int8;
  /**
   * Zero-based position of the extracted attachment within a message MIME part walk.
   */
  part_index: number;
  size_bytes: number | null;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  ip_address: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: Int8;
}

export interface EmailVerificationTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token_hash: string;
  user_id: Int8;
}

export interface Lists {
  id: Generated<number>;
  name: string;
  source_folder: string | null;
  tracked: Generated<boolean>;
}

export interface MailboxReceipts {
  attempt_count: Generated<number>;
  blob_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  internal_date: Timestamp | null;
  jmap_email_id: string;
  last_error: string | null;
  list_id: number;
  mailbox_id: string;
  message_id_header: string | null;
  parsed_message_id: string | null;
  raw_rfc822: Buffer;
  raw_sha256: string;
  source_folder: string;
  status: string;
  stored_message_db_id: Int8 | null;
  updated_at: Generated<Timestamp>;
}

export interface MailboxSyncState {
  email_query_state: string | null;
  last_push_event_id: string | null;
  last_reconciled_at: Timestamp | null;
  last_successful_sync_at: Timestamp | null;
  list_id: number;
  mailbox_id: string;
  source_folder: string;
  updated_at: Generated<Timestamp>;
}

export interface Messages {
  archive_month: Timestamp | null;
  body: string | null;
  body_search: Generated<string | null>;
  from_email: string | null;
  from_name: string | null;
  id: Generated<Int8>;
  in_reply_to: string | null;
  list_id: number;
  message_id: string;
  refs: string[] | null;
  sent_at: Timestamp | null;
  sent_at_approx: Generated<boolean>;
  subject: string | null;
  thread_id: string;
}

export interface PasswordResetTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token_hash: string;
  user_id: Int8;
}

export interface People {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface PeopleEmails {
  email: string;
  id: Generated<number>;
  person_id: number;
}

export interface SchemaMigrations {
  version: string;
}

export interface ThreadFollows {
  anchor_message_id: Int8;
  created_at: Generated<Timestamp>;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface ThreadReadProgress {
  last_read_message_id: Int8;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface Threads {
  id: string;
  last_activity_at: Timestamp | null;
  list_id: number;
  message_count: Generated<number>;
  started_at: Timestamp | null;
  subject: string | null;
  thread_id: string;
}

export interface ThreadTracking {
  anchor_message_id: Int8;
  created_at: Generated<Timestamp>;
  manual_followed_at: Timestamp | null;
  participated_at: Timestamp | null;
  participation_suppressed_at: Timestamp | null;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface UserEmailClaims {
  claim_kind: string;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  user_id: Int8;
}

export interface UserEmails {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  is_primary: Generated<boolean>;
  user_id: Int8;
  verified_at: Timestamp;
}

export interface Users {
  created_at: Generated<Timestamp>;
  disable_reason: string | null;
  disabled_at: Timestamp | null;
  display_name: string | null;
  id: Generated<Int8>;
  last_login_at: Timestamp | null;
  password_hash: string;
  role: Generated<string>;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  analytics_by_dow: AnalyticsByDow;
  analytics_by_hour: AnalyticsByHour;
  analytics_by_month: AnalyticsByMonth;
  analytics_messages_last_24h: AnalyticsMessagesLast24h;
  analytics_summary: AnalyticsSummary;
  analytics_top_senders: AnalyticsTopSenders;
  attachments: Attachments;
  auth_sessions: AuthSessions;
  email_verification_tokens: EmailVerificationTokens;
  lists: Lists;
  mailbox_receipts: MailboxReceipts;
  mailbox_sync_state: MailboxSyncState;
  messages: Messages;
  password_reset_tokens: PasswordResetTokens;
  people: People;
  people_emails: PeopleEmails;
  schema_migrations: SchemaMigrations;
  thread_follows: ThreadFollows;
  thread_read_progress: ThreadReadProgress;
  thread_tracking: ThreadTracking;
  threads: Threads;
  user_email_claims: UserEmailClaims;
  user_emails: UserEmails;
  users: Users;
}
